### ISSUE TITLE
Problem with Tiny Tina grenades and class mods

### ISSUE THREAD

**Issue by Morphyne** [gibbed/Gibbed.Borderlands2#113]
I do have a slight issue that I am not sure what is causing it. There are a few items I have put in my backpack in Gibbed and when I bring the save back into my ps4 the items are no longer there.  Also as a disclaimer, I am using the recently posted method by BuFu_EVO for PS4 saves 
https://www.se7ensins.com/forums/threads/gibbed-ps4-saves-no-ps3-needed.1769835/
This method involves converting your PS4 save to an XBOX360 save in order to use Gibbed and then converting back to PS4 save file.  Save Wizard is required.

magic missile (purple) : BL2(BwAAAADIsAkAFQegEBG93v+/AqIdgwsDBkMGQwdDCIMVw///AOI=)

chain lightning:
BL2(BwAAAAD8HQkAFQmgEBG93v+/AaIdQwsDBkMGw/9/CMMVw///AeI=)

true neural monk:
BL2(BwAAAAAyGwkfFAewEBG9ngjBAUEAwf///////////38DAQghAME=) 

What is also strange is that I have a legit acquired level 44 purple magic missile and a level 80 chain lightning on my ps4 save that does not show up when I import into Gibbed.  I get a message give me the option to remove the items or leave them and they cannot be edited. The item name does not show up in my backpack list.  Nor do they show up listed as unknown in the backpack. 

Here is the message from what I copied to the notepad:
System.InvalidOperationException: don't know how to remap sublibrary 21 for set 9!
   at Gibbed.Borderlands2.FileFormats.AssetLibraryManagerHelpers.Lookup(AssetLibraryManager assetLibraryManager, PackedAssetReference packed, Platform platform, Int32 setId, AssetGroup group)
   at Gibbed.Borderlands2.FileFormats.Items.BaseItem.Unpack(PackedItem packed, Platform platform)
   at Gibbed.Borderlands2.FileFormats.Items.PackedDataHelper`2.Decode(Byte[] data, Platform platform)
   at Gibbed.Borderlands2.SaveEdit.BackpackViewModel.ImportData(WillowTwoPlayerSaveGame saveGame, Platform platform)

System.InvalidOperationException: don't know how to remap sublibrary 21 for set 9!
   at Gibbed.Borderlands2.FileFormats.AssetLibraryManagerHelpers.Lookup(AssetLibraryManager assetLibraryManager, PackedAssetReference packed, Platform platform, Int32 setId, AssetGroup group)
   at Gibbed.Borderlands2.FileFormats.Items.BaseItem.Unpack(PackedItem packed, Platform platform)
   at Gibbed.Borderlands2.FileFormats.Items.PackedDataHelper`2.Decode(Byte[] data, Platform platform)
   at Gibbed.Borderlands2.SaveEdit.BackpackViewModel.ImportData(WillowTwoPlayerSaveGame saveGame, Platform platform)

When I select no( to not remove the items) and I complete my Gibbed session I save and convert back to my PS4 file as normal.  When I bring the save back to my PS4 the grenades now back up.

Is there an issue with some of the Tiny Tina stuff?  Everything else I have tried so far has worked without issue.  Any advise would be very much appreciated.

**Comment by gibbed** [comment]
This is because you're erroneously treating PS4 data as 360 data. 360 saves have some different asset library IDs compared to other platforms.
