### ISSUE TITLE
Cannot open save file in Gibbed; exception thrown

### ISSUE THREAD

**Issue by Re-VelatoR** [gibbed/Gibbed.Borderlands2#124]
Getting the following error code whenever I try to open my BL2 save.

> ---------------------------
Error
---------------------------
An exception was thrown (press Ctrl+C to copy):

System.OverflowException: Array dimensions exceeded supported range.

   at Gibbed.Borderlands2.FileFormats.SaveFile.Deserialize(Stream input, Platform platform, DeserializeSettings settings)

   at Gibbed.Borderlands2.SaveEdit.ShellViewModel.<>c__DisplayClass62_0.<ReadSave>b__0()

   at Caliburn.Micro.Contrib.Results.DelegateResult.Execute(ActionExecutionContext context)
---------------------------
OK   
---------------------------

Here is the steps I've taken up to this point:
1. Cross save PS4 file back to PS3.
2. Copy PS3 file onto USB drive.
3. Copy PS3 into the 'Saves' folder of BruteForce Save Data (4.7.4)
4. Decrypt file in Bruteforce, apply SHA1 update (Gibbed returned a related error If I did not apply it)
5. Attempt to open file with Gibbed (selecting PS3 format of .sav), above error returned.

Is it possible that the issue is caused by my PS3 version having absolutely none of the DLC? I started playing on the Handsome collection and borrowed a friend's old PS3 and a copy of the game (he has none of the DLC). If that's the case, what DLCs would I need to purchase? Or is the issue more complex than that?

Attached file is the save I'm trying to edit, I was previously trying to edit my Lv80 OP4 character, and it was returning a different thrown exception, viewable here: [https://www.reddit.com/r/bl2modding/comments/ck0si2/help_with_gibbed_save_editing/](url)

New file is a fresh Lv1 character.

[PS3.zip](https://github.com/gibbed/Gibbed.Borderlands2/files/3452631/PS3.zip)

**Comment by xcier** [comment]
SHA1 keys are broken for every version of bruteforce. Since all of the issues lately it's best to just take your save and put everything on a new save. If Rick would work with apocalyptech I feel like we would see a huge spike in what gibbed can do. Rick is amazing and apocalyptech has revamped Easy player data (which can allow us to edit ps4 saves)

**Comment by gibbed** [comment]
@Re-VelatoR I'm getting "invalid SHA1 hash" with the save you've provided. Did you provide the decrypted save or the encrypted save? If you provided the encrypted save, please attach a decrypted one.

**Comment by Re-VelatoR** [comment]
[PS3.zip](https://github.com/gibbed/Gibbed.Borderlands2/files/3453532/PS3.zip)
@gibbed Here you go. This should be decrypted.

**Comment by gibbed** [comment]
I missed the "Apply SHA1 update" part in your original post. Where is this coming from? Because that explains why this decrypted data is garbage.

**Comment by Re-VelatoR** [comment]
I need to apply the SHA1 update under the cheats section after decrypting, otherwise I get an "Invalid SHA1 hash" error. But I'm still met with that much longer error afterwards anyways. I 
[PS3.zip](https://github.com/gibbed/Gibbed.Borderlands2/files/3453592/PS3.zip)

Here is the decrypted version without the SHA1 update. Hopefully you can figure out what's going on.

**Comment by gibbed** [comment]
The invalid SHA1 hash error is a legitimate check, if you get it-- it means decryption failed. Recalculating the SHA1 hash to the garbage data doesn't do anything.

I'll have to add further sanity checks to give more reasonable error messages, but the samples you've provided are not valid save files.

**Comment by Re-VelatoR** [comment]
Which is odd, because that's a freshly created Lv1 character on PS3. I'll cross save my Lv80 character from PS4 over again, and send you it. Would you prefer encrypted so you can do the process from the beginning?

Do note that I don't have any of the DLC on the PS3 version, while the Handsome Collection on PS4 comes with it all preinstalled (save for Commander Lilith). If that's a problem, what DLCs do I need to pick up on PS3?

**Comment by gibbed** [comment]
I don't have any tools to interact with encrypted PS3 saves, so I would appreciate decrypted save files. But any platform specific encryption problems are beyond the scope of the save editor, since that's not a thing the save editor does.

I don't know about DLC, so I couldn't tell you.

**Comment by Re-VelatoR** [comment]
Should I do anything like Verify PFD and Rebuild before decrypting, or will that mess things up?

**Comment by gibbed** [comment]
I couldn't tell you, I haven't used those tools.

**Comment by Re-VelatoR** [comment]
[PS3.zip](https://github.com/gibbed/Gibbed.Borderlands2/files/3453699/PS3.zip)

Here's My Lv80 save, cross-saved from PS4 and ran through decryption in BruteForce 4.7.4

**Comment by Re-VelatoR** [comment]
I'm going to try actually loading the save on the PS3, then saving and quitting to see if I have any better luck. I think an issue might be that the save is still defined within the parameters of the PS4 version, so if I force an adjustment to the PS3 version of the game by loading and saving it, it COULD alleviate my issues,

**Comment by Re-VelatoR** [comment]
It did not. I'm completely lost now. BruteForce is saying that the decryption went through without any errors, but what you're saying is that if the save editor returns an "Invalid SHA1 hash" error, the file isn't decrypted. So I'm not really sure what's going on.
