### ISSUE TITLE
Hello, i have an problem.

### ISSUE THREAD

**Issue by Sydecadus** [gibbed/Gibbed.Borderlands2#143]
---------------------------
Error
---------------------------
An exception was thrown (press Ctrl+C to copy):

System.UnauthorizedAccessException: Access to the path is denied.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)

   at System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)

   at System.IO.FileStream.FlushWrite(Boolean calledFromFinalizer)

   at System.IO.FileStream.Dispose(Boolean disposing)

   at System.IO.Stream.Close()

   at Gibbed.Borderlands2.SaveEdit.ShellViewModel.WriteSave(String savePath, SaveFile saveFile)

   at Caliburn.Micro.Contrib.Results.DelegateResult.Execute(ActionExecutionContext context)
---------------------------
OK   
---------------------------

**Comment by Sydecadus** [comment]
Hello, I got it fixed, it was my ransomware protection going off again..

**Comment by Sydecadus** [comment]
Closed
