### ISSUE TITLE
Tiny Tina items not loading on switch.

### ISSUE THREAD

**Issue by BraveNZ** [gibbed/Gibbed.Borderlands2#149]
Hi,

Some Tiny Tiny items are not loading into the game on Switch.  Some i have tested are the blockade shield and dragons keep alignment class mods, chaotic evil etc.  They will also not load back into gibbed from a Switch save.  It is not all tiny tina items as the guns seem to work fine.

Thanks
Brave

**Comment by gibbed** [comment]
If you could provide me with a save with any of these items working I could check into why it might not be working.

**Comment by BraveNZ** [comment]
This file should contain the blockade and some alignment mods but receives an error stating some items wont load upon loading in gibbed.

[Save0001.zip](https://github.com/gibbed/Gibbed.Borderlands2/files/5126763/Save0001.zip)

cheers

**Comment by xcier** [comment]
i've heard a lot of people are having this issue btw you're not alone

**Comment by Keukotis** [comment]
I'll add in another confirmation that while Tiny Tina weapons do work fine, the other equipment does not. The attached save has an Antagonist shield in it, but this shield will not load. Attempting to load the save gives this error:

> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
> Parameter name: invalid asset index 7 in sublibrary GD_Aster_EllieDressData
>    at Gibbed.Borderlands2.GameInfo.AssetSublibraryDefinition.GetAsset(Int32 index)
>    at Gibbed.Borderlands2.FileFormats.Items.BaseItem.Unpack(PackedItem packed, Platform platform)
>    at Gibbed.Borderlands2.FileFormats.Items.PackedDataHelper`2.Decode(Byte[] data, Platform platform)
>    at Gibbed.Borderlands2.SaveEdit.BackpackViewModel.ImportData(WillowTwoPlayerSaveGame saveGame, Platform platform)
[Save0001.zip](https://github.com/gibbed/Gibbed.Borderlands2/files/5742741/Save0001.zip)
