### ISSUE TITLE
Stumped

### ISSUE THREAD

**Issue by DVRX000** [gibbed/Gibbed.Borderlands2#157]
So this error has been popping up recently and it's never happened up until now, my items are only modded through BLCMM and BL2Reborn.
---------------------------
Error
---------------------------
An exception was thrown (press Ctrl+C to copy):

System.FormatException: invalid PlayerMark value

   at Gibbed.Borderlands2.SaveEdit.BackpackViewModel.ImportData(WillowTwoPlayerSaveGame saveGame, Platform platform)

   at Gibbed.Borderlands2.SaveEdit.ShellViewModel.<>c__DisplayClass62_0.<ReadSave>b__0()

   at Caliburn.Micro.Contrib.Results.DelegateResult.Execute(ActionExecutionContext context)
---------------------------
OK   
---------------------------

**Comment by FromDarkHell** [comment]
This is known if you've ever used before: [BL2 Deathtrap Shield](https://github.com/RLNT/bl2_deathtrapshield) by Relentless on your Gaige

**Comment by DVRX000** [comment]
> This is known if you've ever used before: [BL2 Deathtrap Shield](https://github.com/RLNT/bl2_deathtrapshield) by Relentless on your Gaige

So what should i do to make my save "gibbable" again? Do i just delete the mod and go back in then save and quit?

**Comment by FromDarkHell** [comment]
You'll want to load the save with the mod active and then disable the Deathtrap shield marker
