### ISSUE TITLE
Tiny Tina's DLC items not working on Nintendo Switch

### ISSUE THREAD

**Issue by E1ite007** [gibbed/Gibbed.Borderlands2#175]
Hello,

I've noticed that when modifying a Nintendo Switch gamesave to include Tiny Tina's gear the game just deletes the items from the backpack.
I've also read that this is a common issue so far and also that loading a Switch gamesave that has legally obtained Tiny Tina's gear gives errors when trying to save.

Is there a workaround for this or will it get fixed in a future?
Thanks a lot.

**Comment by GreemDev** [comment]
> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: invalid asset index 34 in sublibrary GD_Mercenary_Items_Aster
   at Gibbed.Borderlands2.GameInfo.AssetSublibraryDefinition.GetAsset(Int32 index)
   at Gibbed.Borderlands2.FileFormats.Items.BaseItem.Unpack(PackedItem packed, Platform platform)
   at Gibbed.Borderlands2.FileFormats.Items.PackedDataHelper`2.Decode(Byte[] data, Platform platform)
   at Gibbed.Borderlands2.SaveEdit.BackpackViewModel.ImportData(WillowTwoPlayerSaveGame saveGame, Platform platform)

> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: invalid asset index 38 in sublibrary GD_Mercenary_Items_Aster
   at Gibbed.Borderlands2.GameInfo.AssetSublibraryDefinition.GetAsset(Int32 index)
   at Gibbed.Borderlands2.FileFormats.Items.BaseItem.Unpack(PackedItem packed, Platform platform)
   at Gibbed.Borderlands2.FileFormats.Items.PackedDataHelper`2.Decode(Byte[] data, Platform platform)
   at Gibbed.Borderlands2.SaveEdit.BackpackViewModel.ImportData(WillowTwoPlayerSaveGame saveGame, Platform platform)

Encountered when loading a legitimately obtained Gunzerker Monk class mod.
