### ISSUE TITLE
System Unauthorized Access Exception

### ISSUE THREAD

**Issue by JakeyIsCanadian** [gibbed/Gibbed.Borderlands2#24]
---------------------------
Error
---------------------------
An exception was thrown (press Ctrl+C to copy):

System.UnauthorizedAccessException: Access to the path 'C:\Users\Richa\Documents\My Games\Borderlands 2\WillowGame\SaveData\76561198142786156\Save0005.sav' is denied.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)

   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)

   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)

   at Gibbed.Borderlands2.SaveEdit.ShellViewModel.<>c__DisplayClass59_0.<WriteSave>b__1()

   at Caliburn.Micro.Contrib.Results.DelegateResult.Execute(ActionExecutionContext context)
---------------------------
OK   
---------------------------
This always pops up after I try to edit my save files, I've also installed the latest version. How can I fix this? 
Thanks

**Comment by gibbed** [comment]
Is this when opening or saving? If it's when saving, the file is probably write locked somehow or something is blocking access to writing the file.

**Comment by JakeyIsCanadian** [comment]
It is when I try saving the changes I make. I can load my save files fine, and create new save files, however when I try to replace the old save files that message pops up.

**Comment by JakeyIsCanadian** [comment]
This happens when I try to save. I can load and create new save files, but when I save them with changes, that message always pops up.
