### ISSUE TITLE
Cannot open or save files while running the source code

### ISSUE THREAD

**Issue by TroostJames** [gibbed/Gibbed.Borderlands2#4]
It almost seems as though gibbed I/O is missing some of the functions needed to run this.

here is the error

System.MissingMethodException: Method not found: 'System.IO.MemoryStream Gibbed.IO.StreamHelpers.ReadToMemoryStream(System.IO.Stream, Int64)'.

   at Gibbed.Borderlands2.FileFormats.SaveFile.Deserialize(Stream input, Platform platform, DeserializeSettings settings)

   at Gibbed.Borderlands2.SaveEdit.ShellViewModel.<>c__DisplayClass58_0.<ReadSave>b__2() in C:\Users\User\Desktop\Gibbed.Borderlands2-master\projects\Gibbed.Borderlands2.SaveEdit\ShellViewModel.cs:line 332

   at Caliburn.Micro.Contrib.Results.DelegateResult.Execute(ActionExecutionContext context) in R:\CMContrib\src\CMContrib.SL\Results\DelegateResult.cs:line 22

**Comment by gibbed** [comment]
Did you solve your problem?

**Comment by TroostJames** [comment]
Yes thank you. I had downloaded the project off github and it had pointers
for two of the folders i created the project without those folders and
tried importing them into the project after i realised they were missing. I
ended up just starting a new project with all of the files at the start and
worked great!

**Comment by gibbed** [comment]
Ah yes, I use submodules, so either you can go directly to the linked submodules and grab their code or if you use git directly you can do "git submodules init; git submodules update".
