### ISSUE TITLE
Error when trying to save changes

### ISSUE THREAD

**Issue by Top-Nep** [gibbed/Gibbed.Borderlands2#61]
Whenever I attempt to save any changes I get this error message, I tried looking it up and the only thing that I found was that a file could be write locked or something like that. Me being not too great with this sort of thing had no idea what that meant so I tried to look that up and could not find anything that made any sort of sense to me so hopefully I can ask for help here. I have pasted the error below, thank you for your time.

---------------------------
Error
---------------------------
An exception was thrown (press Ctrl+C to copy):

System.UnauthorizedAccessException: Access to the path is denied.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)

   at System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)

   at System.IO.FileStream.FlushWrite(Boolean calledFromFinalizer)

   at System.IO.FileStream.Dispose(Boolean disposing)

   at System.IO.Stream.Close()

   at Gibbed.Borderlands2.SaveEdit.ShellViewModel.<>c__DisplayClass59_0.<WriteSave>b__1() in c:\projects\gibbed-borderlands2\projects\Gibbed.Borderlands2.SaveEdit\ShellViewModel.cs:line 571

   at Caliburn.Micro.Contrib.Results.DelegateResult.Execute(ActionExecutionContext context) in R:\CMContrib\src\CMContrib.SL\Results\DelegateResult.cs:line 22
---------------------------
OK   
---------------------------

**Comment by gibbed** [comment]
It could be write locked or it doesn't have permission to write to that location. You could try saving it to a new location then copying that file over to the correct one?

**Comment by Top-Nep** [comment]
That doesn't seem to work either.

**Comment by Top-Nep** [comment]
Just tried disabling my windows defender and that worked... Sorry for the trouble, but thank you for trying.
